# Generated by Django 3.1.6 on 2021-02-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=20)),
                ('contactno1', models.IntegerField()),
                ('contactno2', models.IntegerField()),
                ('linkedin', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(max_length=50)),
                ('board', models.TextField(max_length=50)),
                ('degree', models.TextField(max_length=50)),
                ('startingdate', models.TextField(max_length=20)),
                ('endingdate', models.TextField(max_length=20)),
                ('result', models.TextField(max_length=10)),
                ('percentage', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField(max_length=20)),
                ('previousDesignation', models.TextField(max_length=20)),
                ('startingDate', models.TextField(max_length=20)),
                ('endingDate', models.TextField(max_length=20)),
                ('responsibilities', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.TextField(max_length=50)),
                ('CNIC', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('profile_pic', models.ImageField(default='place.png', upload_to='')),
                ('education', models.ManyToManyField(default=None, to='dashboard.ProfileEducation')),
                ('experience', models.ManyToManyField(default=None, to='dashboard.ProfileExperience')),
                ('skills', models.ManyToManyField(default=None, to='dashboard.ProfileSkills')),
            ],
        ),
    ]
