# Generated by Django 3.1.6 on 2021-02-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='CNIC',
        ),
    ]
