# Generated by Django 3.1.6 on 2021-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_profile_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.ManyToManyField(default=None, to='dashboard.ProfileContact'),
        ),
    ]
