# Generated by Django 3.1.6 on 2021-02-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profedu', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomend', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.ManyToManyField(default=None, to='dashboard.ProfileCertificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profedu',
            field=models.ManyToManyField(default=None, to='dashboard.ProfessionalEducation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(default=None, to='dashboard.ProfileProession'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profinfo',
            field=models.ManyToManyField(default=None, to='dashboard.Profileinfo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommend',
            field=models.ManyToManyField(default=None, to='dashboard.Recommendations'),
        ),
    ]
