# Generated by Django 3.1.6 on 2021-02-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210225_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='contactno1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='contactno2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='ProfileContact',
        ),
    ]
