# Generated by Django 3.1.6 on 2021-02-26 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_profile_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='award',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profedu',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profinfo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommend',
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ManyToManyField(default=None, to='dashboard.ProfileCertificate')),
                ('profedu', models.ManyToManyField(default=None, to='dashboard.ProfessionalEducation')),
                ('profession', models.ManyToManyField(default=None, to='dashboard.ProfileProession')),
                ('profinfo', models.ManyToManyField(default=None, to='dashboard.Profileinfo')),
                ('recommend', models.ManyToManyField(default=None, to='dashboard.Recommendations')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
