# Generated by Django 3.1.6 on 2021-02-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210226_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='profedu',
        ),
    ]
