# Generated by Django 3.1.6 on 2021-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_cv_profedu'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='recomendby',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
