# Generated by Django 3.1.6 on 2021-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumetitle', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.ManyToManyField(default=None, to='dashboard.cvtitle'),
        ),
    ]
