# Generated by Django 3.1.6 on 2021-03-04 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20210227_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAreaofexpertisecv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaofexpertisecv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAwardscv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awcv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBooksAuthoredcv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookscv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCertificatecv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certcv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileIntroductioncv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introcv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProfessioncv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileReferencescv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refcv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTitlecv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlecv2', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_expertisecv2', models.ManyToManyField(default=None, to='dashboard.ProfileAreaofexpertisecv2')),
                ('awardscv2', models.ManyToManyField(default=None, to='dashboard.ProfileAwardscv2')),
                ('books_authored', models.ManyToManyField(default=None, to='dashboard.ProfileBooksAuthoredcv2')),
                ('certificatecv2', models.ManyToManyField(default=None, to='dashboard.ProfileCertificatecv2')),
                ('introductioncv2', models.ManyToManyField(default=None, to='dashboard.ProfileIntroductioncv2')),
                ('professsioncv2', models.ManyToManyField(default=None, to='dashboard.ProfileProfessioncv2')),
                ('referencescv2', models.ManyToManyField(default=None, to='dashboard.ProfileReferencescv2')),
                ('titlecv2', models.ManyToManyField(default=None, to='dashboard.ProfileTitlecv2')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
