# Generated by Django 3.1.6 on 2021-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210304_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereferencescv2',
            name='emailcv2',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profilereferencescv2',
            name='orgcv2',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
